#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
-p 0.0.0.0:3000:3000 \
--name=spiking-model-visualizer \
-v "$(pwd)":/app \
louisross/spiking-model-visualizer:1.0 \
bash

#docker run -p 5000:5000 -d -v /home/louis/github/spiking-model-persist/h5:/data hdfgroup/h5serv:0.1.dev